Repository sss-develops/query-server, pull requests merged in 2023-04, with the labels that each got.

#36 build, feature: 멀티 데이터 소스를 적용한다.
  query-server/src/main/java/project/goorm/queryserver/QueryServerApplication.java
  query-server/src/main/java/project/goorm/queryserver/common/configuration/rdb/DataSourceConfiguration.java
  query-server/src/main/java/project/goorm/queryserver/common/configuration/rdb/DynamicRoutingDataSource.java
Labels: feature, build

#40 bug: 커서 단위 테스트와 회사 이름 API 통합 테스트의 버그를 고친다.
  query-server/src/test/java/project/goorm/queryserver/test/integration/search/CompanySearchByNameIntegrationTest.java
  query-server/src/test/java/project/goorm/queryserver/test/unit/cursor/CursorTestArgumentResolver.java
  query-server/src/test/java/project/goorm/queryserver/test/unit/cursor/CursorUnitTest.java
Labels: bug

#43 test: kafka설정을 변경한다.
  query-server/src/test/java/project/goorm/queryserver/common/configuration/rdb/DatabaseTestBase.java
Labels: test

#46 refactor: 회사 이름 검색 API 통합 테스트의 DisplayName을 설정한다.
  query-server/src/test/java/project/goorm/queryserver/test/integration/search/CompanySearchByNameIntegrationTest.java
Labels: refactor

#48 build: Config-server와 연동하며 RefreshScope을 추가한다.
  query-server/src/main/java/project/goorm/queryserver/QueryServerApplication.java
Labels: build

#50 build: Spring Config Client 의존성을 추가한다.
  query-server/build.gradle
Labels: build

#52 bug: git에서 충돌나는 부분을 제거한다.
  query-server/src/test/java/project/goorm/queryserver/common/configuration/rdb/DatabaseTestBase.java
Labels: bug

#55 test: test용 설정파일을 추가한다.
  query-server/src/test/resources/application-test.yml
Labels: bug

#58 bug: redis 설정을 변경한다.
  query-server/build.gradle
  query-server/src/main/java/project/goorm/queryserver/common/configuration/redis/RedisConfiguration.java
  query-server/src/test/java/project/goorm/queryserver/common/configuration/redis/EmbeddedRedisConfiguration.java
Labels: bug, test
